/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RpcSplatRouteImport } from './routes/rpc/$'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ProtectedTeamRouteImport } from './routes/_protected/team'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedProjectsRouteImport } from './routes/_protected/projects'
import { Route as ProtectedIntegrationsRouteImport } from './routes/_protected/integrations'
import { Route as ProtectedHelpRouteImport } from './routes/_protected/help'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedBillingRouteImport } from './routes/_protected/billing'
import { Route as ProtectedApiKeysRouteImport } from './routes/_protected/api-keys'
import { Route as ProtectedApiDocsRouteImport } from './routes/_protected/api-docs'
import { Route as ProtectedAnalyticsRouteImport } from './routes/_protected/analytics'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as ApiOpenapiJsonRouteImport } from './routes/api/openapi.json'
import { Route as ApiAuthSignOutRouteImport } from './routes/api/auth/sign-out'
import { Route as ApiAuthOkRouteImport } from './routes/api/auth/ok'
import { Route as ApiAuthGetSessionRouteImport } from './routes/api/auth/get-session'
import { Route as ApiAuthSignUpEmailRouteImport } from './routes/api/auth/sign-up/email'
import { Route as ApiAuthSignInSocialRouteImport } from './routes/api/auth/sign-in/social'
import { Route as ApiAuthSignInEmailRouteImport } from './routes/api/auth/sign-in/email'
import { Route as ApiAuthCallbackProviderRouteImport } from './routes/api/auth/callback/$provider'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RpcSplatRoute = RpcSplatRouteImport.update({
  id: '/rpc/$',
  path: '/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedTeamRoute = ProtectedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProjectsRoute = ProtectedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedIntegrationsRoute = ProtectedIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedHelpRoute = ProtectedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedBillingRoute = ProtectedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedApiKeysRoute = ProtectedApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedApiDocsRoute = ProtectedApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAnalyticsRoute = ProtectedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/_auth/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/_auth/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiJsonRoute = ApiOpenapiJsonRouteImport.update({
  id: '/api/openapi/json',
  path: '/api/openapi/json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignOutRoute = ApiAuthSignOutRouteImport.update({
  id: '/api/auth/sign-out',
  path: '/api/auth/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthOkRoute = ApiAuthOkRouteImport.update({
  id: '/api/auth/ok',
  path: '/api/auth/ok',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGetSessionRoute = ApiAuthGetSessionRouteImport.update({
  id: '/api/auth/get-session',
  path: '/api/auth/get-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignUpEmailRoute = ApiAuthSignUpEmailRouteImport.update({
  id: '/api/auth/sign-up/email',
  path: '/api/auth/sign-up/email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignInSocialRoute = ApiAuthSignInSocialRouteImport.update({
  id: '/api/auth/sign-in/social',
  path: '/api/auth/sign-in/social',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignInEmailRoute = ApiAuthSignInEmailRouteImport.update({
  id: '/api/auth/sign-in/email',
  path: '/api/auth/sign-in/email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackProviderRoute = ApiAuthCallbackProviderRouteImport.update({
  id: '/api/auth/callback/$provider',
  path: '/api/auth/callback/$provider',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/analytics': typeof ProtectedAnalyticsRoute
  '/api-docs': typeof ProtectedApiDocsRoute
  '/api-keys': typeof ProtectedApiKeysRoute
  '/billing': typeof ProtectedBillingRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/help': typeof ProtectedHelpRoute
  '/integrations': typeof ProtectedIntegrationsRoute
  '/projects': typeof ProtectedProjectsRoute
  '/settings': typeof ProtectedSettingsRoute
  '/team': typeof ProtectedTeamRoute
  '/api/health': typeof ApiHealthRoute
  '/rpc/$': typeof RpcSplatRoute
  '/api/auth/get-session': typeof ApiAuthGetSessionRoute
  '/api/auth/ok': typeof ApiAuthOkRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/api/openapi/json': typeof ApiOpenapiJsonRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/auth/callback/$provider': typeof ApiAuthCallbackProviderRoute
  '/api/auth/sign-in/email': typeof ApiAuthSignInEmailRoute
  '/api/auth/sign-in/social': typeof ApiAuthSignInSocialRoute
  '/api/auth/sign-up/email': typeof ApiAuthSignUpEmailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/analytics': typeof ProtectedAnalyticsRoute
  '/api-docs': typeof ProtectedApiDocsRoute
  '/api-keys': typeof ProtectedApiKeysRoute
  '/billing': typeof ProtectedBillingRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/help': typeof ProtectedHelpRoute
  '/integrations': typeof ProtectedIntegrationsRoute
  '/projects': typeof ProtectedProjectsRoute
  '/settings': typeof ProtectedSettingsRoute
  '/team': typeof ProtectedTeamRoute
  '/api/health': typeof ApiHealthRoute
  '/rpc/$': typeof RpcSplatRoute
  '/api/auth/get-session': typeof ApiAuthGetSessionRoute
  '/api/auth/ok': typeof ApiAuthOkRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/api/openapi/json': typeof ApiOpenapiJsonRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/auth/callback/$provider': typeof ApiAuthCallbackProviderRoute
  '/api/auth/sign-in/email': typeof ApiAuthSignInEmailRoute
  '/api/auth/sign-in/social': typeof ApiAuthSignInSocialRoute
  '/api/auth/sign-up/email': typeof ApiAuthSignUpEmailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/docs': typeof DocsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_protected/analytics': typeof ProtectedAnalyticsRoute
  '/_protected/api-docs': typeof ProtectedApiDocsRoute
  '/_protected/api-keys': typeof ProtectedApiKeysRoute
  '/_protected/billing': typeof ProtectedBillingRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/help': typeof ProtectedHelpRoute
  '/_protected/integrations': typeof ProtectedIntegrationsRoute
  '/_protected/projects': typeof ProtectedProjectsRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/team': typeof ProtectedTeamRoute
  '/api/health': typeof ApiHealthRoute
  '/rpc/$': typeof RpcSplatRoute
  '/api/auth/get-session': typeof ApiAuthGetSessionRoute
  '/api/auth/ok': typeof ApiAuthOkRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/api/openapi/json': typeof ApiOpenapiJsonRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/auth/callback/$provider': typeof ApiAuthCallbackProviderRoute
  '/api/auth/sign-in/email': typeof ApiAuthSignInEmailRoute
  '/api/auth/sign-in/social': typeof ApiAuthSignInSocialRoute
  '/api/auth/sign-up/email': typeof ApiAuthSignUpEmailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/sitemap.xml'
    | '/sign-in'
    | '/sign-up'
    | '/analytics'
    | '/api-docs'
    | '/api-keys'
    | '/billing'
    | '/dashboard'
    | '/help'
    | '/integrations'
    | '/projects'
    | '/settings'
    | '/team'
    | '/api/health'
    | '/rpc/$'
    | '/api/auth/get-session'
    | '/api/auth/ok'
    | '/api/auth/sign-out'
    | '/api/openapi/json'
    | '/api/v1/$'
    | '/api/auth/callback/$provider'
    | '/api/auth/sign-in/email'
    | '/api/auth/sign-in/social'
    | '/api/auth/sign-up/email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/sitemap.xml'
    | '/sign-in'
    | '/sign-up'
    | '/analytics'
    | '/api-docs'
    | '/api-keys'
    | '/billing'
    | '/dashboard'
    | '/help'
    | '/integrations'
    | '/projects'
    | '/settings'
    | '/team'
    | '/api/health'
    | '/rpc/$'
    | '/api/auth/get-session'
    | '/api/auth/ok'
    | '/api/auth/sign-out'
    | '/api/openapi/json'
    | '/api/v1/$'
    | '/api/auth/callback/$provider'
    | '/api/auth/sign-in/email'
    | '/api/auth/sign-in/social'
    | '/api/auth/sign-up/email'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/docs'
    | '/sitemap.xml'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_protected/analytics'
    | '/_protected/api-docs'
    | '/_protected/api-keys'
    | '/_protected/billing'
    | '/_protected/dashboard'
    | '/_protected/help'
    | '/_protected/integrations'
    | '/_protected/projects'
    | '/_protected/settings'
    | '/_protected/team'
    | '/api/health'
    | '/rpc/$'
    | '/api/auth/get-session'
    | '/api/auth/ok'
    | '/api/auth/sign-out'
    | '/api/openapi/json'
    | '/api/v1/$'
    | '/api/auth/callback/$provider'
    | '/api/auth/sign-in/email'
    | '/api/auth/sign-in/social'
    | '/api/auth/sign-up/email'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  DocsRoute: typeof DocsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  ApiHealthRoute: typeof ApiHealthRoute
  RpcSplatRoute: typeof RpcSplatRoute
  ApiAuthGetSessionRoute: typeof ApiAuthGetSessionRoute
  ApiAuthOkRoute: typeof ApiAuthOkRoute
  ApiAuthSignOutRoute: typeof ApiAuthSignOutRoute
  ApiOpenapiJsonRoute: typeof ApiOpenapiJsonRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  ApiAuthCallbackProviderRoute: typeof ApiAuthCallbackProviderRoute
  ApiAuthSignInEmailRoute: typeof ApiAuthSignInEmailRoute
  ApiAuthSignInSocialRoute: typeof ApiAuthSignInSocialRoute
  ApiAuthSignUpEmailRoute: typeof ApiAuthSignUpEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpc/$': {
      id: '/rpc/$'
      path: '/rpc/$'
      fullPath: '/rpc/$'
      preLoaderRoute: typeof RpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/team': {
      id: '/_protected/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof ProtectedTeamRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/projects': {
      id: '/_protected/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProtectedProjectsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/integrations': {
      id: '/_protected/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof ProtectedIntegrationsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/help': {
      id: '/_protected/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof ProtectedHelpRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/billing': {
      id: '/_protected/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof ProtectedBillingRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/api-keys': {
      id: '/_protected/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ProtectedApiKeysRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/api-docs': {
      id: '/_protected/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ProtectedApiDocsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/analytics': {
      id: '/_protected/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof ProtectedAnalyticsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi/json': {
      id: '/api/openapi/json'
      path: '/api/openapi/json'
      fullPath: '/api/openapi/json'
      preLoaderRoute: typeof ApiOpenapiJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-out': {
      id: '/api/auth/sign-out'
      path: '/api/auth/sign-out'
      fullPath: '/api/auth/sign-out'
      preLoaderRoute: typeof ApiAuthSignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/ok': {
      id: '/api/auth/ok'
      path: '/api/auth/ok'
      fullPath: '/api/auth/ok'
      preLoaderRoute: typeof ApiAuthOkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/get-session': {
      id: '/api/auth/get-session'
      path: '/api/auth/get-session'
      fullPath: '/api/auth/get-session'
      preLoaderRoute: typeof ApiAuthGetSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-up/email': {
      id: '/api/auth/sign-up/email'
      path: '/api/auth/sign-up/email'
      fullPath: '/api/auth/sign-up/email'
      preLoaderRoute: typeof ApiAuthSignUpEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-in/social': {
      id: '/api/auth/sign-in/social'
      path: '/api/auth/sign-in/social'
      fullPath: '/api/auth/sign-in/social'
      preLoaderRoute: typeof ApiAuthSignInSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-in/email': {
      id: '/api/auth/sign-in/email'
      path: '/api/auth/sign-in/email'
      fullPath: '/api/auth/sign-in/email'
      preLoaderRoute: typeof ApiAuthSignInEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback/$provider': {
      id: '/api/auth/callback/$provider'
      path: '/api/auth/callback/$provider'
      fullPath: '/api/auth/callback/$provider'
      preLoaderRoute: typeof ApiAuthCallbackProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedAnalyticsRoute: typeof ProtectedAnalyticsRoute
  ProtectedApiDocsRoute: typeof ProtectedApiDocsRoute
  ProtectedApiKeysRoute: typeof ProtectedApiKeysRoute
  ProtectedBillingRoute: typeof ProtectedBillingRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedHelpRoute: typeof ProtectedHelpRoute
  ProtectedIntegrationsRoute: typeof ProtectedIntegrationsRoute
  ProtectedProjectsRoute: typeof ProtectedProjectsRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedTeamRoute: typeof ProtectedTeamRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAnalyticsRoute: ProtectedAnalyticsRoute,
  ProtectedApiDocsRoute: ProtectedApiDocsRoute,
  ProtectedApiKeysRoute: ProtectedApiKeysRoute,
  ProtectedBillingRoute: ProtectedBillingRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedHelpRoute: ProtectedHelpRoute,
  ProtectedIntegrationsRoute: ProtectedIntegrationsRoute,
  ProtectedProjectsRoute: ProtectedProjectsRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedTeamRoute: ProtectedTeamRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  DocsRoute: DocsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  ApiHealthRoute: ApiHealthRoute,
  RpcSplatRoute: RpcSplatRoute,
  ApiAuthGetSessionRoute: ApiAuthGetSessionRoute,
  ApiAuthOkRoute: ApiAuthOkRoute,
  ApiAuthSignOutRoute: ApiAuthSignOutRoute,
  ApiOpenapiJsonRoute: ApiOpenapiJsonRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
  ApiAuthCallbackProviderRoute: ApiAuthCallbackProviderRoute,
  ApiAuthSignInEmailRoute: ApiAuthSignInEmailRoute,
  ApiAuthSignInSocialRoute: ApiAuthSignInSocialRoute,
  ApiAuthSignUpEmailRoute: ApiAuthSignUpEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
