/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RpcSplatRouteImport } from './routes/rpc/$'
import { Route as InviteIdRouteImport } from './routes/invite.$id'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as PublicPricingRouteImport } from './routes/_public/pricing'
import { Route as PublicCoverageRouteImport } from './routes/_public/coverage'
import { Route as PublicChangelogRouteImport } from './routes/_public/changelog'
import { Route as ProtectedZonesRouteImport } from './routes/_protected/zones'
import { Route as ProtectedWebhooksRouteImport } from './routes/_protected/webhooks'
import { Route as ProtectedTeamRouteImport } from './routes/_protected/team'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedSdkPlaygroundRouteImport } from './routes/_protected/sdk-playground'
import { Route as ProtectedProjectsRouteImport } from './routes/_protected/projects'
import { Route as ProtectedIntegrationsRouteImport } from './routes/_protected/integrations'
import { Route as ProtectedHelpRouteImport } from './routes/_protected/help'
import { Route as ProtectedDevicesRouteImport } from './routes/_protected/devices'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedComponentsRouteImport } from './routes/_protected/components'
import { Route as ProtectedBillingRouteImport } from './routes/_protected/billing'
import { Route as ProtectedBatchRouteImport } from './routes/_protected/batch'
import { Route as ProtectedApiKeysRouteImport } from './routes/_protected/api-keys'
import { Route as ProtectedApiDocsRouteImport } from './routes/_protected/api-docs'
import { Route as ProtectedAnalyticsRouteImport } from './routes/_protected/analytics'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as DotwellKnownApiCatalogRouteImport } from './routes/[.]well-known.api-catalog'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as ApiOpenapiJsonRouteImport } from './routes/api/openapi.json'
import { Route as ApiAuthSignOutRouteImport } from './routes/api/auth/sign-out'
import { Route as ApiAuthOkRouteImport } from './routes/api/auth/ok'
import { Route as ApiAuthGetSessionRouteImport } from './routes/api/auth/get-session'
import { Route as PublicLegalTermsRouteImport } from './routes/_public/legal/terms'
import { Route as PublicLegalPrivacyRouteImport } from './routes/_public/legal/privacy'
import { Route as PublicLegalAcceptableUseRouteImport } from './routes/_public/legal/acceptable-use'
import { Route as ApiAuthSignUpEmailRouteImport } from './routes/api/auth/sign-up/email'
import { Route as ApiAuthSignInSocialRouteImport } from './routes/api/auth/sign-in/social'
import { Route as ApiAuthSignInEmailRouteImport } from './routes/api/auth/sign-in/email'
import { Route as ApiAuthCallbackProviderRouteImport } from './routes/api/auth/callback/$provider'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RpcSplatRoute = RpcSplatRouteImport.update({
  id: '/rpc/$',
  path: '/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteIdRoute = InviteIdRouteImport.update({
  id: '/invite/$id',
  path: '/invite/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicPricingRoute = PublicPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCoverageRoute = PublicCoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => PublicRoute,
} as any)
const PublicChangelogRoute = PublicChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => PublicRoute,
} as any)
const ProtectedZonesRoute = ProtectedZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedWebhooksRoute = ProtectedWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTeamRoute = ProtectedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSdkPlaygroundRoute = ProtectedSdkPlaygroundRouteImport.update({
  id: '/sdk-playground',
  path: '/sdk-playground',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProjectsRoute = ProtectedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedIntegrationsRoute = ProtectedIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedHelpRoute = ProtectedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDevicesRoute = ProtectedDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedComponentsRoute = ProtectedComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedBillingRoute = ProtectedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedBatchRoute = ProtectedBatchRouteImport.update({
  id: '/batch',
  path: '/batch',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedApiKeysRoute = ProtectedApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedApiDocsRoute = ProtectedApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAnalyticsRoute = ProtectedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/_auth/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/_auth/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/_auth/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/_auth/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownApiCatalogRoute = DotwellKnownApiCatalogRouteImport.update({
  id: '/.well-known/api-catalog',
  path: '/.well-known/api-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiJsonRoute = ApiOpenapiJsonRouteImport.update({
  id: '/api/openapi/json',
  path: '/api/openapi/json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignOutRoute = ApiAuthSignOutRouteImport.update({
  id: '/api/auth/sign-out',
  path: '/api/auth/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthOkRoute = ApiAuthOkRouteImport.update({
  id: '/api/auth/ok',
  path: '/api/auth/ok',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGetSessionRoute = ApiAuthGetSessionRouteImport.update({
  id: '/api/auth/get-session',
  path: '/api/auth/get-session',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLegalTermsRoute = PublicLegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLegalPrivacyRoute = PublicLegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLegalAcceptableUseRoute =
  PublicLegalAcceptableUseRouteImport.update({
    id: '/legal/acceptable-use',
    path: '/legal/acceptable-use',
    getParentRoute: () => PublicRoute,
  } as any)
const ApiAuthSignUpEmailRoute = ApiAuthSignUpEmailRouteImport.update({
  id: '/api/auth/sign-up/email',
  path: '/api/auth/sign-up/email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignInSocialRoute = ApiAuthSignInSocialRouteImport.update({
  id: '/api/auth/sign-in/social',
  path: '/api/auth/sign-in/social',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignInEmailRoute = ApiAuthSignInEmailRouteImport.update({
  id: '/api/auth/sign-in/email',
  path: '/api/auth/sign-in/email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackProviderRoute = ApiAuthCallbackProviderRouteImport.update({
  id: '/api/auth/callback/$provider',
  path: '/api/auth/callback/$provider',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/analytics': typeof ProtectedAnalyticsRoute
  '/api-docs': typeof ProtectedApiDocsRoute
  '/api-keys': typeof ProtectedApiKeysRoute
  '/batch': typeof ProtectedBatchRoute
  '/billing': typeof ProtectedBillingRoute
  '/components': typeof ProtectedComponentsRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/devices': typeof ProtectedDevicesRoute
  '/help': typeof ProtectedHelpRoute
  '/integrations': typeof ProtectedIntegrationsRoute
  '/projects': typeof ProtectedProjectsRoute
  '/sdk-playground': typeof ProtectedSdkPlaygroundRoute
  '/settings': typeof ProtectedSettingsRoute
  '/team': typeof ProtectedTeamRoute
  '/webhooks': typeof ProtectedWebhooksRoute
  '/zones': typeof ProtectedZonesRoute
  '/changelog': typeof PublicChangelogRoute
  '/coverage': typeof PublicCoverageRoute
  '/pricing': typeof PublicPricingRoute
  '/api/health': typeof ApiHealthRoute
  '/invite/$id': typeof InviteIdRoute
  '/rpc/$': typeof RpcSplatRoute
  '/legal/acceptable-use': typeof PublicLegalAcceptableUseRoute
  '/legal/privacy': typeof PublicLegalPrivacyRoute
  '/legal/terms': typeof PublicLegalTermsRoute
  '/api/auth/get-session': typeof ApiAuthGetSessionRoute
  '/api/auth/ok': typeof ApiAuthOkRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/api/openapi/json': typeof ApiOpenapiJsonRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/auth/callback/$provider': typeof ApiAuthCallbackProviderRoute
  '/api/auth/sign-in/email': typeof ApiAuthSignInEmailRoute
  '/api/auth/sign-in/social': typeof ApiAuthSignInSocialRoute
  '/api/auth/sign-up/email': typeof ApiAuthSignUpEmailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/analytics': typeof ProtectedAnalyticsRoute
  '/api-docs': typeof ProtectedApiDocsRoute
  '/api-keys': typeof ProtectedApiKeysRoute
  '/batch': typeof ProtectedBatchRoute
  '/billing': typeof ProtectedBillingRoute
  '/components': typeof ProtectedComponentsRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/devices': typeof ProtectedDevicesRoute
  '/help': typeof ProtectedHelpRoute
  '/integrations': typeof ProtectedIntegrationsRoute
  '/projects': typeof ProtectedProjectsRoute
  '/sdk-playground': typeof ProtectedSdkPlaygroundRoute
  '/settings': typeof ProtectedSettingsRoute
  '/team': typeof ProtectedTeamRoute
  '/webhooks': typeof ProtectedWebhooksRoute
  '/zones': typeof ProtectedZonesRoute
  '/changelog': typeof PublicChangelogRoute
  '/coverage': typeof PublicCoverageRoute
  '/pricing': typeof PublicPricingRoute
  '/api/health': typeof ApiHealthRoute
  '/invite/$id': typeof InviteIdRoute
  '/rpc/$': typeof RpcSplatRoute
  '/legal/acceptable-use': typeof PublicLegalAcceptableUseRoute
  '/legal/privacy': typeof PublicLegalPrivacyRoute
  '/legal/terms': typeof PublicLegalTermsRoute
  '/api/auth/get-session': typeof ApiAuthGetSessionRoute
  '/api/auth/ok': typeof ApiAuthOkRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/api/openapi/json': typeof ApiOpenapiJsonRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/auth/callback/$provider': typeof ApiAuthCallbackProviderRoute
  '/api/auth/sign-in/email': typeof ApiAuthSignInEmailRoute
  '/api/auth/sign-in/social': typeof ApiAuthSignInSocialRoute
  '/api/auth/sign-up/email': typeof ApiAuthSignUpEmailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/docs': typeof DocsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_protected/analytics': typeof ProtectedAnalyticsRoute
  '/_protected/api-docs': typeof ProtectedApiDocsRoute
  '/_protected/api-keys': typeof ProtectedApiKeysRoute
  '/_protected/batch': typeof ProtectedBatchRoute
  '/_protected/billing': typeof ProtectedBillingRoute
  '/_protected/components': typeof ProtectedComponentsRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/devices': typeof ProtectedDevicesRoute
  '/_protected/help': typeof ProtectedHelpRoute
  '/_protected/integrations': typeof ProtectedIntegrationsRoute
  '/_protected/projects': typeof ProtectedProjectsRoute
  '/_protected/sdk-playground': typeof ProtectedSdkPlaygroundRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/team': typeof ProtectedTeamRoute
  '/_protected/webhooks': typeof ProtectedWebhooksRoute
  '/_protected/zones': typeof ProtectedZonesRoute
  '/_public/changelog': typeof PublicChangelogRoute
  '/_public/coverage': typeof PublicCoverageRoute
  '/_public/pricing': typeof PublicPricingRoute
  '/api/health': typeof ApiHealthRoute
  '/invite/$id': typeof InviteIdRoute
  '/rpc/$': typeof RpcSplatRoute
  '/_public/legal/acceptable-use': typeof PublicLegalAcceptableUseRoute
  '/_public/legal/privacy': typeof PublicLegalPrivacyRoute
  '/_public/legal/terms': typeof PublicLegalTermsRoute
  '/api/auth/get-session': typeof ApiAuthGetSessionRoute
  '/api/auth/ok': typeof ApiAuthOkRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/api/openapi/json': typeof ApiOpenapiJsonRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/auth/callback/$provider': typeof ApiAuthCallbackProviderRoute
  '/api/auth/sign-in/email': typeof ApiAuthSignInEmailRoute
  '/api/auth/sign-in/social': typeof ApiAuthSignInSocialRoute
  '/api/auth/sign-up/email': typeof ApiAuthSignUpEmailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/sitemap.xml'
    | '/.well-known/api-catalog'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/analytics'
    | '/api-docs'
    | '/api-keys'
    | '/batch'
    | '/billing'
    | '/components'
    | '/dashboard'
    | '/devices'
    | '/help'
    | '/integrations'
    | '/projects'
    | '/sdk-playground'
    | '/settings'
    | '/team'
    | '/webhooks'
    | '/zones'
    | '/changelog'
    | '/coverage'
    | '/pricing'
    | '/api/health'
    | '/invite/$id'
    | '/rpc/$'
    | '/legal/acceptable-use'
    | '/legal/privacy'
    | '/legal/terms'
    | '/api/auth/get-session'
    | '/api/auth/ok'
    | '/api/auth/sign-out'
    | '/api/openapi/json'
    | '/api/v1/$'
    | '/api/auth/callback/$provider'
    | '/api/auth/sign-in/email'
    | '/api/auth/sign-in/social'
    | '/api/auth/sign-up/email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/sitemap.xml'
    | '/.well-known/api-catalog'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/analytics'
    | '/api-docs'
    | '/api-keys'
    | '/batch'
    | '/billing'
    | '/components'
    | '/dashboard'
    | '/devices'
    | '/help'
    | '/integrations'
    | '/projects'
    | '/sdk-playground'
    | '/settings'
    | '/team'
    | '/webhooks'
    | '/zones'
    | '/changelog'
    | '/coverage'
    | '/pricing'
    | '/api/health'
    | '/invite/$id'
    | '/rpc/$'
    | '/legal/acceptable-use'
    | '/legal/privacy'
    | '/legal/terms'
    | '/api/auth/get-session'
    | '/api/auth/ok'
    | '/api/auth/sign-out'
    | '/api/openapi/json'
    | '/api/v1/$'
    | '/api/auth/callback/$provider'
    | '/api/auth/sign-in/email'
    | '/api/auth/sign-in/social'
    | '/api/auth/sign-up/email'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_public'
    | '/docs'
    | '/sitemap.xml'
    | '/.well-known/api-catalog'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_protected/analytics'
    | '/_protected/api-docs'
    | '/_protected/api-keys'
    | '/_protected/batch'
    | '/_protected/billing'
    | '/_protected/components'
    | '/_protected/dashboard'
    | '/_protected/devices'
    | '/_protected/help'
    | '/_protected/integrations'
    | '/_protected/projects'
    | '/_protected/sdk-playground'
    | '/_protected/settings'
    | '/_protected/team'
    | '/_protected/webhooks'
    | '/_protected/zones'
    | '/_public/changelog'
    | '/_public/coverage'
    | '/_public/pricing'
    | '/api/health'
    | '/invite/$id'
    | '/rpc/$'
    | '/_public/legal/acceptable-use'
    | '/_public/legal/privacy'
    | '/_public/legal/terms'
    | '/api/auth/get-session'
    | '/api/auth/ok'
    | '/api/auth/sign-out'
    | '/api/openapi/json'
    | '/api/v1/$'
    | '/api/auth/callback/$provider'
    | '/api/auth/sign-in/email'
    | '/api/auth/sign-in/social'
    | '/api/auth/sign-up/email'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  DocsRoute: typeof DocsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DotwellKnownApiCatalogRoute: typeof DotwellKnownApiCatalogRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  ApiHealthRoute: typeof ApiHealthRoute
  InviteIdRoute: typeof InviteIdRoute
  RpcSplatRoute: typeof RpcSplatRoute
  ApiAuthGetSessionRoute: typeof ApiAuthGetSessionRoute
  ApiAuthOkRoute: typeof ApiAuthOkRoute
  ApiAuthSignOutRoute: typeof ApiAuthSignOutRoute
  ApiOpenapiJsonRoute: typeof ApiOpenapiJsonRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  ApiAuthCallbackProviderRoute: typeof ApiAuthCallbackProviderRoute
  ApiAuthSignInEmailRoute: typeof ApiAuthSignInEmailRoute
  ApiAuthSignInSocialRoute: typeof ApiAuthSignInSocialRoute
  ApiAuthSignUpEmailRoute: typeof ApiAuthSignUpEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpc/$': {
      id: '/rpc/$'
      path: '/rpc/$'
      fullPath: '/rpc/$'
      preLoaderRoute: typeof RpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$id': {
      id: '/invite/$id'
      path: '/invite/$id'
      fullPath: '/invite/$id'
      preLoaderRoute: typeof InviteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/pricing': {
      id: '/_public/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PublicPricingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/coverage': {
      id: '/_public/coverage'
      path: '/coverage'
      fullPath: '/coverage'
      preLoaderRoute: typeof PublicCoverageRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/changelog': {
      id: '/_public/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof PublicChangelogRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_protected/zones': {
      id: '/_protected/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof ProtectedZonesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/webhooks': {
      id: '/_protected/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof ProtectedWebhooksRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/team': {
      id: '/_protected/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof ProtectedTeamRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/sdk-playground': {
      id: '/_protected/sdk-playground'
      path: '/sdk-playground'
      fullPath: '/sdk-playground'
      preLoaderRoute: typeof ProtectedSdkPlaygroundRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/projects': {
      id: '/_protected/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProtectedProjectsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/integrations': {
      id: '/_protected/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof ProtectedIntegrationsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/help': {
      id: '/_protected/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof ProtectedHelpRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/devices': {
      id: '/_protected/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof ProtectedDevicesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/components': {
      id: '/_protected/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ProtectedComponentsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/billing': {
      id: '/_protected/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof ProtectedBillingRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/batch': {
      id: '/_protected/batch'
      path: '/batch'
      fullPath: '/batch'
      preLoaderRoute: typeof ProtectedBatchRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/api-keys': {
      id: '/_protected/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ProtectedApiKeysRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/api-docs': {
      id: '/_protected/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ProtectedApiDocsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/analytics': {
      id: '/_protected/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof ProtectedAnalyticsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/api-catalog': {
      id: '/.well-known/api-catalog'
      path: '/.well-known/api-catalog'
      fullPath: '/.well-known/api-catalog'
      preLoaderRoute: typeof DotwellKnownApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi/json': {
      id: '/api/openapi/json'
      path: '/api/openapi/json'
      fullPath: '/api/openapi/json'
      preLoaderRoute: typeof ApiOpenapiJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-out': {
      id: '/api/auth/sign-out'
      path: '/api/auth/sign-out'
      fullPath: '/api/auth/sign-out'
      preLoaderRoute: typeof ApiAuthSignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/ok': {
      id: '/api/auth/ok'
      path: '/api/auth/ok'
      fullPath: '/api/auth/ok'
      preLoaderRoute: typeof ApiAuthOkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/get-session': {
      id: '/api/auth/get-session'
      path: '/api/auth/get-session'
      fullPath: '/api/auth/get-session'
      preLoaderRoute: typeof ApiAuthGetSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/legal/terms': {
      id: '/_public/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof PublicLegalTermsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/legal/privacy': {
      id: '/_public/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof PublicLegalPrivacyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/legal/acceptable-use': {
      id: '/_public/legal/acceptable-use'
      path: '/legal/acceptable-use'
      fullPath: '/legal/acceptable-use'
      preLoaderRoute: typeof PublicLegalAcceptableUseRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/auth/sign-up/email': {
      id: '/api/auth/sign-up/email'
      path: '/api/auth/sign-up/email'
      fullPath: '/api/auth/sign-up/email'
      preLoaderRoute: typeof ApiAuthSignUpEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-in/social': {
      id: '/api/auth/sign-in/social'
      path: '/api/auth/sign-in/social'
      fullPath: '/api/auth/sign-in/social'
      preLoaderRoute: typeof ApiAuthSignInSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-in/email': {
      id: '/api/auth/sign-in/email'
      path: '/api/auth/sign-in/email'
      fullPath: '/api/auth/sign-in/email'
      preLoaderRoute: typeof ApiAuthSignInEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback/$provider': {
      id: '/api/auth/callback/$provider'
      path: '/api/auth/callback/$provider'
      fullPath: '/api/auth/callback/$provider'
      preLoaderRoute: typeof ApiAuthCallbackProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedAnalyticsRoute: typeof ProtectedAnalyticsRoute
  ProtectedApiDocsRoute: typeof ProtectedApiDocsRoute
  ProtectedApiKeysRoute: typeof ProtectedApiKeysRoute
  ProtectedBatchRoute: typeof ProtectedBatchRoute
  ProtectedBillingRoute: typeof ProtectedBillingRoute
  ProtectedComponentsRoute: typeof ProtectedComponentsRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedDevicesRoute: typeof ProtectedDevicesRoute
  ProtectedHelpRoute: typeof ProtectedHelpRoute
  ProtectedIntegrationsRoute: typeof ProtectedIntegrationsRoute
  ProtectedProjectsRoute: typeof ProtectedProjectsRoute
  ProtectedSdkPlaygroundRoute: typeof ProtectedSdkPlaygroundRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedTeamRoute: typeof ProtectedTeamRoute
  ProtectedWebhooksRoute: typeof ProtectedWebhooksRoute
  ProtectedZonesRoute: typeof ProtectedZonesRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAnalyticsRoute: ProtectedAnalyticsRoute,
  ProtectedApiDocsRoute: ProtectedApiDocsRoute,
  ProtectedApiKeysRoute: ProtectedApiKeysRoute,
  ProtectedBatchRoute: ProtectedBatchRoute,
  ProtectedBillingRoute: ProtectedBillingRoute,
  ProtectedComponentsRoute: ProtectedComponentsRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedDevicesRoute: ProtectedDevicesRoute,
  ProtectedHelpRoute: ProtectedHelpRoute,
  ProtectedIntegrationsRoute: ProtectedIntegrationsRoute,
  ProtectedProjectsRoute: ProtectedProjectsRoute,
  ProtectedSdkPlaygroundRoute: ProtectedSdkPlaygroundRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedTeamRoute: ProtectedTeamRoute,
  ProtectedWebhooksRoute: ProtectedWebhooksRoute,
  ProtectedZonesRoute: ProtectedZonesRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicRouteChildren {
  PublicChangelogRoute: typeof PublicChangelogRoute
  PublicCoverageRoute: typeof PublicCoverageRoute
  PublicPricingRoute: typeof PublicPricingRoute
  PublicLegalAcceptableUseRoute: typeof PublicLegalAcceptableUseRoute
  PublicLegalPrivacyRoute: typeof PublicLegalPrivacyRoute
  PublicLegalTermsRoute: typeof PublicLegalTermsRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicChangelogRoute: PublicChangelogRoute,
  PublicCoverageRoute: PublicCoverageRoute,
  PublicPricingRoute: PublicPricingRoute,
  PublicLegalAcceptableUseRoute: PublicLegalAcceptableUseRoute,
  PublicLegalPrivacyRoute: PublicLegalPrivacyRoute,
  PublicLegalTermsRoute: PublicLegalTermsRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  DocsRoute: DocsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DotwellKnownApiCatalogRoute: DotwellKnownApiCatalogRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  ApiHealthRoute: ApiHealthRoute,
  InviteIdRoute: InviteIdRoute,
  RpcSplatRoute: RpcSplatRoute,
  ApiAuthGetSessionRoute: ApiAuthGetSessionRoute,
  ApiAuthOkRoute: ApiAuthOkRoute,
  ApiAuthSignOutRoute: ApiAuthSignOutRoute,
  ApiOpenapiJsonRoute: ApiOpenapiJsonRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
  ApiAuthCallbackProviderRoute: ApiAuthCallbackProviderRoute,
  ApiAuthSignInEmailRoute: ApiAuthSignInEmailRoute,
  ApiAuthSignInSocialRoute: ApiAuthSignInSocialRoute,
  ApiAuthSignUpEmailRoute: ApiAuthSignUpEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
